name = "cctv-stream-worker"
main = "worker.js"
compatibility_date = "2026-03-01"

[[durable_objects.bindings]]
name = "STREAM_DO"
class_name = "StreamStorage"

[[migrations]]
tag = "v1"
new_classes = ["StreamStorage"]
